## Prototype Orbital Model

Predicting the velocity of Mars (VX,VY,VZ) based on its position coordinates (X,Y,Z)

In [1]:
import numpy
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import tensorflow

In [2]:
eph_df=pd.read_csv('ephemeris.csv', index_col=False)

C:\Users\yasha\AppData\Local\Temp\ipykernel_41112\4238620832.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  eph_df=pd.read_csv('ephemeris.csv', index_col=False)

In [3]:
eph_df.head()

,JDTDB,Date,X,Y,Z,VX,VY,VZ,LT,RG,RR
0,2442412.5,A.D. 1974-Dec-31 00:00:00.0000,-1.180764e+08,-1.959401e+08,-1.194484e+06,21.689503,-10.413457,-0.752096,763.096615,2.287706e+08,-2.271733
1,2442413.5,A.D. 1975-Jan-01 00:00:00.0000,-1.161976e+08,-1.968317e+08,-1.259414e+06,21.801780,-10.224586,-0.750906,762.441530,2.285742e+08,-2.274295
2,2442414.5,A.D. 1975-Jan-02 00:00:00.0000,-1.143091e+08,-1.977069e+08,-1.324239e+06,21.912527,-10.034381,-0.749651,761.785732,2.283776e+08,-2.276676
3,2442415.5,A.D. 1975-Jan-03 00:00:00.0000,-1.124111e+08,-1.985656e+08,-1.388952e+06,22.021728,-9.842853,-0.748330,761.129274,2.281808e+08,-2.278875
4,2442416.5,A.D. 1975-Jan-04 00:00:00.0000,-1.105038e+08,-1.994077e+08,-1.453548e+06,22.129364,-9.650010,-0.746942,760.472209,2.279838e+08,-2.280891

In [4]:
X=eph_df[['X','Y','Z']].values
y=eph_df[['VX','VY','VZ']].values
X

array([[-1.18076388e+08, -1.95940123e+08, -1.19448380e+06],
       [-1.16197554e+08, -1.96831696e+08, -1.25941397e+06],
       [-1.14309085e+08, -1.97706893e+08, -1.32423851e+06],
       ...,
       [-7.31743786e+07,  2.28864604e+08,  6.61162179e+06],
       [-7.50883462e+07,  2.28405018e+08,  6.64894964e+06],
       [-7.69970556e+07,  2.27929208e+08,  6.68580843e+06]])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)
len(y_test)

5480

In [6]:
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train=scaler.transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential()
model.add(Dense(6, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(3))
model.compile(optimizer='rmsprop',loss='mse')

In [ ]:
model.fit(x=X_train,y=y_train,epochs=50)

Epoch 1/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 748us/step - loss: 177.1568
Epoch 2/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 736us/step - loss: 123.5609
Epoch 3/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - loss: 85.7851
Epoch 4/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - loss: 55.9086
Epoch 5/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - loss: 15.2370
Epoch 6/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 744us/step - loss: 0.4318
Epoch 7/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 742us/step - loss: 0.3507
Epoch 8/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 739us/step - loss: 0.3298
Epoch 9/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step - loss: 0.3118
Epoch 10/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 787us/step - loss: 0.2987
Epoch 11/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - loss: 0.2888
Epoch 12/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - loss: 0.2801
Epoch 13/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 782us/step - loss: 0.2716
Epoch 14/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - loss: 0.2621
Epoch 15/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - loss: 0.2512
Epoch 16/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 772us/step - loss: 0.2418
Epoch 17/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - loss: 0.2347
Epoch 18/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - loss: 0.2321
Epoch 19/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 727us/step - loss: 0.2320
Epoch 20/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - loss: 0.2313
Epoch 21/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 730us/step - loss: 0.2306
Epoch 22/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - loss: 0.2312
Epoch 23/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - loss: 0.2316
Epoch 24/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 780us/step - loss: 0.2311
Epoch 25/25
400/400 ━━━━━━━━━━━━━━━━━━━━ 0s 732us/step - loss: 0.2315

In [10]:
test_pred=model.predict(X_test)
test_pred
test_pred=pd.DataFrame(test_pred.reshape(5480,3))
# note you may need to adjust the reshape parameter based on the size of the training set
pred_df=pd.DataFrame(y_test)
pred_df=pd.concat([pred_df,test_pred],axis=1)
pred_df.columns=['True VX','True VY','True VZ','Predicted VX','Predicted VY','Predicted VZ']
pred_df.head()

172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 558us/step

     True VX    True VY   True VZ  Predicted VX  Predicted VY  Predicted VZ
0  23.808888  10.021354 -0.373616     23.738594      9.762461     -0.348106
1  12.666947 -19.113332 -0.711843     12.552896    -18.898602     -0.708202
2  25.164580   2.134370 -0.575137     25.184851      2.427890     -0.551417
3  12.623895 -19.143789 -0.711918     12.518712    -18.895445     -0.706628
4  18.773869  18.433595 -0.074098     18.558357     18.302925     -0.059711

In [45]:
model.evaluate(X_test, y_test)

172/172 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4499

0.44550955295562744